server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/triple?serverTimezone=UTC&characterEncoding=UTF-8
    username: triple
    password: triple
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        show_sql: true
        format_sql: true

    # OSIV 옵션 끄기
    open-in-view: false